### ISSUE TITLE
Compatibility issues

### ISSUE THREAD

**Issue by bagobor** [hpicgs/glbinding#106]
I found 2 cases which doesnt work (compile):

1. glDetachShader(m_vertexShader, GL_VERTEX_SHADER);

2. GLint status(0); glGetShaderiv(shader, GL_COMPILE_STATUS, &status);
    if (GL_TRUE != status) {...}

**Comment by scheibel** [comment]
Hello bagabor,

the OpenGL API (https://www.opengl.org/sdk/docs/man/html/glDetachShader.xhtml) states, that your first example is in fact wrong, as the first parameter has to be a program ID/name and the second parameter has to be a shader ID/name, where you provided a shader ID as first parameter and its type as second parameter.

The second issue is an OpenGL API issue, which either has to be fixed by the KHRONOS group or we have to provide a workaround in our glfixes.xml (see: https://github.com/hpicgs/glbinding/issues/40).

**Comment by bagobor** [comment]
Thanks for your help and good project! I just start to porn third party project to glbinding and it already help to find some errors!
