### ISSUE TITLE
Error while trying to alter texture.

### ISSUE THREAD

**Issue by lukasz1985** [hpicgs/glbinding#107]
This:
 gl::glTexParameteri(gl::GL_TEXTURE_2D, gl::GL_TEXTURE_WRAP_S, gl::GL_REPEAT);

gives me this error:

error: cannot convert 'const gl::GLenum' to 'gl::GLint {aka int}' for argument '3' to 'void gl::glTexParameteri(gl::GLenum, gl::GLenum, gl::GLint)'

Why???!???

**Comment by scheibel** [comment]
This is an issue of the OpenGL API which treats integers equal to enumerations (and glbinding does not). As a workaround, you have to cast the gl::GL_REPEAT to an int (```static_cast<gl::GLint>(gl::GL_REPEAT)```). To be consistent with the naming of the OpenGL API, a method ```glTexParametere``` would be needed (but won't exist due to the equality of enum values and integers).
In globjects, we added an appropriate method for enum values that are automatically cast to an int.

**Comment by scheibel** [comment]
We have a look at a convenient solution for this in #108.
