### ISSUE TITLE
Including <glbinding/gl/gl.h> slows down compilation massively

### ISSUE THREAD

**Issue by mrzzzrm** [hpicgs/glbinding#70]
You probably know about this - is there really nothing that can be done about it? I just cut down the compilation time of a small project from just about 3 minutes to 55 seconds by replacing a dozen or so ```gl.h``` with the actually needed ```types.h```, ```enum.h```, ```bitfield.h```, ```functions.h```... The thing is just, this is a lot of manual work. 
I'd rather like to be able to just include ```gl.h``` and be able to use GL without killing my build times. Can we maybe outsource some non-GL functionality from ```gl.h``` to external headers? Maybe employ defines to disable features we don't need?

(I haven't bothered to figure out what's actually going on in ```gl.h```, just pointing this out in general)

**Comment by scheibel** [comment]
Yeah, we absolutely know about this :laughing: 

First of all, even GLEW exposes comparable amounts in its own ```GL/glew.h``` in its header.
The only reason it is quicker is that is uses ```#defines``` and thus let the preprocessor handle the actual work.
With glbinding, we define actual symbols and use templates to enable type-safety and introspection mechanisms, which are completely handled by the compiler.

Your solution with using the splitted headers is exactly our way to address this issue.

Let me say a few words about your other proposed solutions:

Outsource functionality from ```gl.h```: One of our main goals was to provide an API that is highly compatible to GLEW. So we wanted just one include and one ```using namespace``` as a transformation between GLEW and glbinding projects. The gl.h is as minimal as we think it may be to fulfill this purpose.
For a simple form of splitting the ```gl.h``` one can use the splitted headers.

Using defines: We want to program semantic-rich C++ that uses the preprocessor as least as possible. But if you want to cut down features, you can use the version-tailored headers of ```gl.h``` (e.g., ```gl45core.h```).

Generally, the OpenGL API isn't designed that modularily and at first we took inspiration from the shipped OpenGL headers and GLEW.
Of course, we can even provide per-extension headers and we actually thought about it, but this would further increase manually collecting and using multiple headers.

At least, we thought about tailoring the generation process (as it is done by glLoadGen).

**Comment by cgcostume** [comment]
In addition, we just started to evaluate two different kinds of "arbitrary" categorization of gl commands (see queries tool [queries/main.cpp](https://github.com/hpicgs/glbinding/blob/master/source/tools/queries/main.cpp) and another approach is in logging [scripts/categories.py](https://github.com/hpicgs/glbinding/blob/logging/codegeneration/scripts/categories.py)) that are based on some gl documentation as well as on manual categorization ...  this could be used for further specialization of headers, e.g., ```glrendering.h``` and ```gltextures.h```. I would like this a lot.

We would like to address this issue as follows: we just start providing a categorization in terms of a patch of gl.xml (move categorization.py information to patch.xml) and hope for a positive reception and adoption in terms of official feedback from khronos group as we want this to happen for the current patch.xml in general (note that the patch.xml can be merged into glm.xml automatically) since it partially exposes the incompletion of gl.xml. This, however, is a long way to go and requires a better overall reception/awareness of glbinding ... we are working hard to achieve both (patch.xml and adoption of glbinding).

**Comment by cgcostume** [comment]
please try compilation again, with the current master the times should be faster again ...

**Comment by mrzzzrm** [comment]
Too lazy to take before-after timings, but feels a lot better indeed.
You may remove that "wontfix" tag ;)
